---
name: Config & SQF Check

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  validate:
    name: Validate SQF & Config
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install git+https://github.com/TheWreckingCrewUK/sqf.git
      
    - name: Validate SQF
      run: python3 tools/sqf_validator.py
      
    - name: Validate Config
      run: python3 tools/config_validator.py

  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
          
    - name: Lint (sqflint)
      uses: arma-actions/sqflint@master
      continue-on-error: true # No failure due to many false-positives
