name: Config & SQF Check

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  validate:
    name: Validate SQF & Config
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
      
    - name: Validate SQF
      run: python3 tools/sqf_validator.py
      
    - name: Validate Config
      run: python3 tools/config_validator.py
