name: Arma

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Validate SQF
      run: python3 tools/sqf_validator.py
    - name: Validate Config
      run: python3 tools/config_style_checker.py
    - name: Validate String Tables
      run: python3 tools/check_strings.py
    - name: Check for BOM
      uses: arma-actions/bom-check@master
    - name: Lint (sqflint)
      uses: arma-actions/sqflint@master
    - uses: actions/setup-ruby@v1
    - name: Send Webhook Notification
      if: always()
      env:
        JOB_STATUS: ${{ job.status }}
        WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        HOOK_OS_NAME: ${{ runner.os }}
        WORKFLOW_NAME: ${{ github.workflow }}
      run: |
        echo Status: $JOB_STATUS
        git clone $WEBHOOK_REPO webhook
        bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
      shell: bash
